### ISSUE TITLE
[Bug]: <title>TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tongji-1** [microsoft/graphrag#1328]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

 D:\graphrag-main>poetry run poe index --root ./test/index
Poe => python -m graphrag.index --root ./test/index

Logging enabled at D:\graphrag-main\test\index\output\20241028-011610\reports\indexing-engine.log
Traceback (most recent call last):
  File "D:\Users\22525\anaconda3\envs\yjy\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\22525\anaconda3\envs\yjy\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\graphrag-main\graphrag\index\__main__.py", line 104, in <module>
    index_cli(
  File "D:\graphrag-main\graphrag\index\cli.py", line 132, in index_cli
    outputs = asyncio.run(
  File "D:\Users\22525\anaconda3\envs\yjy\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\22525\anaconda3\envs\yjy\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\graphrag-main\graphrag\api\index.py", line 63, in build_index
    vector_store_type = config.embeddings.vector_store["type"]  # type: ignore
TypeError: 'NoneType' object is not subscriptable

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by EvelynBai** [comment]
same

**Comment by AlonsoGuevara** [comment]
Hi folks!
Please run init and generate a new settings.yaml file.
This will add vector store definitions to your configuration

**Comment by YanSte** [comment]
Still present this issue.
