### ISSUE TITLE
[Bug]:  Error executing verb "generate_text_embeddings" in generate_text_embeddings

### ISSUE THREAD

**Issue by xldistance** [microsoft/graphrag#1426]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

Version 0.4 can create indexes normally, version 0.5 has the following error:
```
19:15:13,178 datashaper.workflow.workflow ERROR Error executing verb "generate_text_embeddings" in generate_text_embeddings: "None of [Index(['id', 'title'], dtype='object')] are in the [columns]"
Traceback (most recent call last):
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\workflows\v1\subflows\generate_text_embeddings.py", line 56, in generate_text_embeddings
    await generate_text_embeddings_flow(
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\flows\generate_text_embeddings.py", line 79, in generate_text_embeddings
    "data": final_community_reports.loc[:, ["id", "title"]]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1377, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1020, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1420, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1360, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexes\base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['id', 'title'], dtype='object')] are in the [columns]"
19:15:13,221 graphrag.callbacks.file_workflow_callbacks INFO Error executing verb "generate_text_embeddings" in generate_text_embeddings: "None of [Index(['id', 'title'], dtype='object')] are in the [columns]" details=None
19:15:13,221 graphrag.index.run.run ERROR error running workflow generate_text_embeddings
Traceback (most recent call last):
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\run\run.py", line 273, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\run\workflow.py", line 105, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\workflows\v1\subflows\generate_text_embeddings.py", line 56, in generate_text_embeddings
    await generate_text_embeddings_flow(
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\graphrag\index\flows\generate_text_embeddings.py", line 79, in generate_text_embeddings
    "data": final_community_reports.loc[:, ["id", "title"]]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1377, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1020, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1420, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1360, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "E:\open-webui-0.3.35\backend\open_webui\python311\Lib\site-packages\pandas\core\indexes\base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['id', 'title'], dtype='object')] are in the [columns]"
19:15:13,222 graphrag.callbacks.file_workflow_callbacks INFO Error running pipeline! details=None
19:15:13,251 graphrag.cli.index ERROR Errors occurred during the pipeline run, see logs for more details.
```

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:0.5.0
- Operating System:windows 11
- Python Version:python 3.11
- Related Issues:

**Comment by xldistance** [comment]
Using gemini to run to generate_text_embeddings fails, using gpt-4o-mini works fine!

**Comment by xldistance** [comment]
It's still a strong gpt-4o model
