### ISSUE TITLE
[Issue]: Unknown LLM type None

### ISSUE THREAD

**Issue by doitslow** [microsoft/graphrag#1427]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Running example use_built_in_workflows encountered with LLM type error. I have created a toy dataset as specified in run.py. 

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Logs and screenshots

ERROR:root:parallel transformation error
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/grag/lib/python3.10/site-packages/datashaper/execution/derive_from_rows_base.py", line 39, in execute
    result = await result
  File "/home/ma-user/work/graphrag/graphrag/index/operations/extract_entities/extract_entities.py", line 130, in run_strategy
    result = await strategy_exec(
  File "/home/ma-user/work/graphrag/graphrag/index/operations/extract_entities/strategies/graph_intelligence.py", line 36, in run_graph_intelligence
    llm = load_llm("entity_extraction", llm_type, callbacks, cache, llm_config)
  File "/home/ma-user/work/graphrag/graphrag/index/llm/load_llm.py", line 61, in load_llm
    raise ValueError(msg)
ValueError: Unknown LLM type None

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by jgbradley1** [comment]
Can you share the initial config file you are using (strip out any api key's before posting please)?
