### ISSUE TITLE
Global Query Issue - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by dipakmeher** [microsoft/graphrag#1435]
I am getting an issue when performing a global query on my knowledge graph. The Knowledge Graph workflow runs successfully, but the global query results in an error. Any assistance in resolving this would be greatly appreciated.

Traceback (most recent call last):
  File "/scratch/dmeher/custom_env/miniforge/envs/graphrag_env/lib/python3.12/site-packages/graphrag/llm/openai/utils.py", line 135, in try_parse_json_object
    result = json.loads(input)
             ^^^^^^^^^^^^^^^^^
  File "/scratch/dmeher/custom_env/miniforge/envs/graphrag_env/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/dmeher/custom_env/miniforge/envs/graphrag_env/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/dmeher/custom_env/miniforge/envs/graphrag_env/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Warning: All map responses have score 0 (i.e., no relevant information found from the dataset), returning a canned 'I do not know' answer. You can try enabling `allow_general_knowledge` to encourage the LLM to incorporate relevant general knowledge, at the risk of increasing hallucinations.

SUCCESS: Global Search Response:
I am sorry but I am unable to answer this question given the provided data.

**Comment by zyy-20** [comment]
same issue，did you solve it？

**Comment by lijiabad** [comment]
I find the issue from [https://github.com/TheAiSingularity/graphrag-local-ollama/issues/44](here) which mentioned 

>  Seems some llms(mistral or qwen2:72b) cannot follow JSON format when \n\nThe response should be JSON formatted as follows:\n{\n    \"points\": [\n        {\"description\": \"Description of point 1 [Data: Reports (report ids)]\", \"score\": score_value},\n        {\"description\": \"Description of point 2 [Data: Reports (report ids)]\", \"score\": score_value}\n    ]\n is in role system's content.

> so I add it to role user's content [graphrag/query/structured_search/global_search/search.py#L379] simply like this :

> search_messages = [ {"role": "system", "content": search_prompt}, {"role": "user", "content": query+'\n\nThe response should be JSON formatted as follows:\n{\n    \"points\": [\n        {\"description\": \"Description of point 1 [Data: Reports (report ids)]\", \"score\": score_value},\n        {\"description\": \"Description of point 2 [Data: Reports (report ids)]\", \"score\": score_value}\n    ]\n'}, ]

> It's a little ugly but it really works :)

when I did so it didnt work (my llm is qwen3:8b, maybe this kind of llm cannot got it; but gpt-oss works)
