### ISSUE TITLE
[Bug]: The chatCompletion operation does not work with the specified model

### ISSUE THREAD

**Issue by guybartal** [microsoft/graphrag#1557]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

It looks like from the log that somehow there's a mix between embedding endpoint and the llm chat endpoint,
it fails after reaching 100% and get stuck like this forever, see screenshot.

logs.json:

```
{
    "type": "error",
    "data": "Error executing verb \"generate_text_embeddings\" in generate_text_embeddings: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}",
    "stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/workflows/v1/generate_text_embeddings.py\", line 96, in workflow\n    await generate_text_embeddings(\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py\", line 100, in generate_text_embeddings\n    await _run_and_snapshot_embeddings(\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py\", line 123, in _run_and_snapshot_embeddings\n    data[\"embedding\"] = await embed_text(\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py\", line 89, in embed_text\n    return await _text_embed_with_vector_store(\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py\", line 179, in _text_embed_with_vector_store\n    result = await strategy_exec(\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py\", line 62, in run\n    embeddings = await _execute(llm, text_batches, ticker, semaphore)\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py\", line 102, in _execute\n    results = await asyncio.gather(*futures)\n  File \"/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py\", line 96, in embed\n    chunk_embeddings = await llm(chunk)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat.py\", line 83, in __call__\n    return await self._text_chat_llm(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/features/tools_parsing.py\", line 120, in __call__\n    return await self._delegate(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py\", line 112, in __call__\n    return await self._invoke(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py\", line 128, in _invoke\n    return await self._decorated_target(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/json.py\", line 71, in invoke\n    return await delegate(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py\", line 109, in invoke\n    result = await execute_with_retry()\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py\", line 93, in execute_with_retry\n    async for a in AsyncRetrying(\n  File \"/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"/usr/local/lib/python3.10/dist-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py\", line 398, in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py\", line 101, in execute_with_retry\n    return await attempt()\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py\", line 78, in attempt\n    return await delegate(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/rate_limiter.py\", line 70, in invoke\n    result = await delegate(prompt, **args)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py\", line 152, in _decorator_target\n    output = await self._execute_llm(prompt, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py\", line 155, in _execute_llm\n    completion = await self._call_completion_or_cache(\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py\", line 127, in _call_completion_or_cache\n    return await self._cache.get_or_insert(\n  File \"/usr/local/lib/python3.10/dist-packages/fnllm/services/cache_interactor.py\", line 50, in get_or_insert\n    entry = await func()\n  File \"/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py\", line 1720, in create\n    return await self._post(\n  File \"/usr/local/lib/python3.10/dist-packages/openai/_base_client.py\", line 1843, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"/usr/local/lib/python3.10/dist-packages/openai/_base_client.py\", line 1537, in request\n    return await self._request(\n  File \"/usr/local/lib/python3.10/dist-packages/openai/_base_client.py\", line 1638, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}\n",
    "source": "Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}",
    "details": null
}
```

indexing-engine.log
```
23:27:04,626 datashaper.workflow.workflow ERROR Error executing verb "generate_text_embeddings" in generate_text_embeddings: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/workflows/v1/generate_text_embeddings.py", line 96, in workflow
    await generate_text_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py", line 100, in generate_text_embeddings
    await _run_and_snapshot_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py", line 123, in _run_and_snapshot_embeddings
    data["embedding"] = await embed_text(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py", line 89, in embed_text
    return await _text_embed_with_vector_store(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py", line 179, in _text_embed_with_vector_store
    result = await strategy_exec(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 62, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 102, in _execute
    results = await asyncio.gather(*futures)
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 96, in embed
    chunk_embeddings = await llm(chunk)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat.py", line 83, in __call__
    return await self._text_chat_llm(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/features/tools_parsing.py", line 120, in __call__
    return await self._delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 112, in __call__
    return await self._invoke(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 128, in _invoke
    return await self._decorated_target(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/json.py", line 71, in invoke
    return await delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 109, in invoke
    result = await execute_with_retry()
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 93, in execute_with_retry
    async for a in AsyncRetrying(
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 101, in execute_with_retry
    return await attempt()
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 78, in attempt
    return await delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/rate_limiter.py", line 70, in invoke
    result = await delegate(prompt, **args)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 152, in _decorator_target
    output = await self._execute_llm(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py", line 155, in _execute_llm
    completion = await self._call_completion_or_cache(
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py", line 127, in _call_completion_or_cache
    return await self._cache.get_or_insert(
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/cache_interactor.py", line 50, in get_or_insert
    entry = await func()
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 1720, in create
    return await self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1537, in request
    return await self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}
23:27:04,628 graphrag.callbacks.file_workflow_callbacks INFO Error executing verb "generate_text_embeddings" in generate_text_embeddings: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}} details=None
23:27:04,632 graphrag.index.run.run ERROR error running workflow generate_text_embeddings
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/run/run.py", line 262, in run_pipeline
    result = await _process_workflow(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/run/workflow.py", line 103, in _process_workflow
    result = await workflow.run(context, callbacks)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/workflows/v1/generate_text_embeddings.py", line 96, in workflow
    await generate_text_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py", line 100, in generate_text_embeddings
    await _run_and_snapshot_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/flows/generate_text_embeddings.py", line 123, in _run_and_snapshot_embeddings
    data["embedding"] = await embed_text(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py", line 89, in embed_text
    return await _text_embed_with_vector_store(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/embed_text.py", line 179, in _text_embed_with_vector_store
    result = await strategy_exec(
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 62, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 102, in _execute
    results = await asyncio.gather(*futures)
  File "/usr/local/lib/python3.10/dist-packages/graphrag/index/operations/embed_text/strategies/openai.py", line 96, in embed
    chunk_embeddings = await llm(chunk)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat.py", line 83, in __call__
    return await self._text_chat_llm(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/features/tools_parsing.py", line 120, in __call__
    return await self._delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 112, in __call__
    return await self._invoke(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 128, in _invoke
    return await self._decorated_target(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/json.py", line 71, in invoke
    return await delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 109, in invoke
    result = await execute_with_retry()
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 93, in execute_with_retry
    async for a in AsyncRetrying(
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 101, in execute_with_retry
    return await attempt()
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/retryer.py", line 78, in attempt
    return await delegate(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/rate_limiter.py", line 70, in invoke
    result = await delegate(prompt, **args)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/base/base.py", line 152, in _decorator_target
    output = await self._execute_llm(prompt, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py", line 155, in _execute_llm
    completion = await self._call_completion_or_cache(
  File "/usr/local/lib/python3.10/dist-packages/fnllm/openai/llm/chat_text.py", line 127, in _call_completion_or_cache
    return await self._cache.get_or_insert(
  File "/usr/local/lib/python3.10/dist-packages/fnllm/services/cache_interactor.py", line 50, in get_or_insert
    entry = await func()
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 1720, in create
    return await self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1537, in request
    return await self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, text-embedding-3-large. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}

```

### Steps to reproduce

1. configure llm and embedding to use azure open ai models gtp-4o-mini and text-embedding-3-large
2. start indexing

### Expected Behavior

indexing should work and finish successfully

### GraphRAG Config Used

```yaml
# Paste your config here
### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.

encoding_model: cl100k_base # this needs to be matched to your model!

llm:
  api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
  type: azure_openai_chat # or azure_openai_chat
  model: gpt-4o-mini
  model_supports_json: true # recommended if this is available for your model.
  # audience: "https://cognitiveservices.azure.com/.default"
  api_base: "https://xxx.openai.azure.com/"
  api_version: 2024-08-01-preview
  # organization: <organization_id>
  deployment_name: gpt-4o-mini

parallelization:
  stagger: 0.3
  num_threads: 1 # 50

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store: 
    type: lancedb
    db_uri: 'output/lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: azure_openai_chat # or azure_openai_embedding
    model: text-embedding-3-large
    api_base: "https://xxx.openai.azure.com/"
    api_version: "2023-05-15"
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    deployment_name: text-embedding-3-large

### Input settings ###

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.json$"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

cache:
  type: file # or blob
  base_dir: "cache"

reporting:
  type: file # or console, blob
  base_dir: "logs"

storage:
  type: file # or blob
  base_dir: "output"

## only turn this on if running `graphrag index` with custom settings
## we normally use `graphrag update` with the defaults
update_index_storage:
  # type: file # or blob
  # base_dir: "update_output"

### Workflow settings ###

skip_workflows: []

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  enabled: false
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  embeddings: false
  transient: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  prompt: "prompts/drift_search_system_prompt.txt"

```

### Logs and screenshots

![Image](https://github.com/user-attachments/assets/870315f2-5a4e-4808-8e5f-eec57cb96bab)

### Additional Information

- GraphRAG Version: 1.0.1
- Operating System: Ubuntu 22.04 (WSL on win 11)
- Python Version: 3.12.4 
- Related Issues:

**Comment by guybartal** [comment]
used the wrong type for embedding setting in config:

`azure_openai_chat`  instead of `azure_openai_embedding`
