### ISSUE TITLE
Symbol Zeros is already exposed as ().

### ISSUE THREAD

**Issue by andysingal** [microsoft/graphrag#343]
i did:
```
https://microsoft.github.io/graphrag/posts/get_started/

 and OPENAI_KEY, python -m graphrag.index --init --root ./ragtest

```
and got error
```
/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
2024-07-03 13:11:26.122415: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/__init__.py", line 40, in <module>
    from .run import run_pipeline, run_pipeline_with_config
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/run.py", line 59, in <module>
    from .verbs import *  # noqa
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/verbs/__init__.py", line 9, in <module>
    from .graph import (
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/verbs/graph/__init__.py", line 10, in <module>
    from .layout import layout_graph
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/__init__.py", line 6, in <module>
    from .layout_graph import layout_graph
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/layout_graph.py", line 13, in <module>
    from graphrag.index.graph.visualization import GraphLayout
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/graph/visualization/__init__.py", line 6, in <module>
    from .compute_umap_positions import compute_umap_positions, get_zero_positions
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py", line 6, in <module>
    import graspologic as gc
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graspologic/__init__.py", line 4, in <module>
    import graspologic.align
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graspologic/align/__init__.py", line 5, in <module>
    from .seedless_procrustes import SeedlessProcrustes
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/graspologic/align/seedless_procrustes.py", line 7, in <module>
    import ot
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/ot/__init__.py", line 21, in <module>
    from . import lp
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/ot/lp/__init__.py", line 20, in <module>
    from .dmmot import dmmot_monge_1dgrid_loss, dmmot_monge_1dgrid_optimize
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/ot/lp/dmmot.py", line 12, in <module>
    from ..backend import get_backend
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/ot/backend.py", line 145, in <module>
    import tensorflow as tf
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/engine/functional.py", line 26, in <module>
    from keras import backend
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/backend/__init__.py", line 3, in <module>
    from keras.backend import experimental
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/backend/experimental/__init__.py", line 3, in <module>
    from keras.src.backend import disable_tf_random_generator
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/__init__.py", line 21, in <module>
    from keras.src import applications
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/applications/__init__.py", line 18, in <module>
    from keras.src.applications.convnext import ConvNeXtBase
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/applications/convnext.py", line 28, in <module>
    from keras.src import backend
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/backend.py", line 35, in <module>
    from keras.src.engine import keras_tensor
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/engine/keras_tensor.py", line 19, in <module>
    from keras.src.utils import object_identity
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/utils/__init__.py", line 20, in <module>
    from keras.src.saving.serialization_lib import deserialize_keras_object
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/saving/serialization_lib.py", line 28, in <module>
    from keras.src.saving.legacy.saved_model.utils import in_tf_saved_model_scope
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/saving/legacy/saved_model/utils.py", line 30, in <module>
    from keras.src.utils.layer_utils import CallFunctionSpec
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/utils/layer_utils.py", line 26, in <module>
    from keras.src import initializers
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/initializers/__init__.py", line 23, in <module>
    from keras.src.initializers import initializers_v1
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/keras/src/initializers/initializers_v1.py", line 32, in <module>
    keras_export(v1=["keras.initializers.Zeros", "keras.initializers.zeros"])(
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 348, in __call__
    self.set_attr(undecorated_func, api_names_attr, self._names)
  File "/Users/ankushsingal/miniconda3/envs/snakes/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 363, in set_attr
    raise SymbolAlreadyExposedError(
tensorflow.python.util.tf_export.SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().
```

**Comment by AlonsoGuevara** [comment]
Hi @andysingal 
Reading through your stack trace it seems to be an issue with Tensorflow's installation. I would suggest trying to re-install it.
