### ISSUE TITLE
How to input

### ISSUE THREAD

**Issue by 6643789wsx** [microsoft/graphrag#378]
I put a.txt file in the.\input folder at the root of the source code. However, I encountered the following error when executing poetry run poe index in the root directory.

There is a file inside the input folder in the root directory. However, I encountered the following error when executing poetry run poe index in the root directory.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\__main__.py", line 76, in <module>
    index_cli(
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\cli.py", line 161, in index_cli
    _run_workflow_async()
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\cli.py", line 149, in _run_workflow_async
    loop.run_until_complete(execute())
  File "E:\usual_app\anaconda\envs\GraphRAG\Lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "E:\usual_app\anaconda\envs\GraphRAG\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "E:\usual_app\anaconda\envs\GraphRAG\Lib\asyncio\tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\cli.py", line 123, in execute
    async for output in run_pipeline_with_config(
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\run.py", line 144, in run_pipeline_with_config
    dataset = dataset if dataset is not None else await _create_input(config.input)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\run.py", line 133, in _create_input
    return await load_input(config, progress_reporter, root_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\input\load_input.py", line 81, in load_input
    results = await loader(config, progress, storage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\pku\20240704_GraphRAG\graphrag\graphrag\index\input\text.py", line 52, in load
    raise ValueError(msg)
ValueError: No text files found in input

**Comment by 6643789wsx** [comment]
python -m graphrag.index --init

**Comment by gogodechen1** [comment]
>> aphrag-env) PS F:\ragtest>
🚀 Reading settings from environment variables
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\__main__.py", line 68, in <module>
    index_cli(
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\cli.py", line 156, in index_cli
    _run_workflow_async()
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\cli.py", line 144, in _run_workflow_async
    loop.run_until_complete(execute())
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "D:\Program Files\Python\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "D:\Program Files\Python\Lib\asyncio\tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\cli.py", line 118, in execute
    async for output in run_pipeline_with_config(
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\run.py", line 144, in run_pipeline_with_config
    dataset = dataset if dataset is not None else await _create_input(config.input)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\run.py", line 133, in _create_input
    return await load_input(config, progress_reporter, root_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\input\load_input.py", line 81, in load_input
    results = await loader(config, progress, storage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhang\graphrag-env\Lib\site-packages\graphrag\index\input\text.py", line 52, in load
    raise ValueError(msg)
ValueError: No text files found in input
⠋ GraphRAG Indexer 

How to fix it？？

**Comment by 2592761383** [comment]
> python -m graphrag.index --init

thanks
