### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for typed-dict embeddings.llm.api_version

### ISSUE THREAD

**Issue by Souradip121** [microsoft/graphrag#512]
### Describe the bug

```(myenv) PS C:\repos\graphrag> python -m graphrag.index --root ./ragtest
🚀 Reading settings from ragtest\settings.yaml
Traceback (most recent call last):
  File "C:\python-3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python-3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\repos\graphrag\myenv\lib\site-packages\graphrag\index\__main__.py", line 68, in <module>
    index_cli(
  File "C:\repos\graphrag\myenv\lib\site-packages\graphrag\index\cli.py", line 92, in index_cli
    pipeline_config: str | PipelineConfig = config or _create_default_config(
  File "C:\repos\graphrag\myenv\lib\site-packages\graphrag\index\cli.py", line 222, in _create_default_config    
    parameters = _read_config_parameters(root, reporter)
  File "C:\repos\graphrag\myenv\lib\site-packages\graphrag\index\cli.py", line 253, in _read_config_parameters   
    return create_graphrag_config(data, root)
  File "C:\repos\graphrag\myenv\lib\site-packages\graphrag\config\create_graphrag_config.py", line 70, in        
create_graphrag_config
    InputModelValidator.validate_python(values, strict=True)
  File "C:\repos\graphrag\myenv\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "C:\repos\graphrag\myenv\lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python        
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes,
context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for typed-dict
embeddings.llm.api_version
  Input should be a valid string [type=string_type, input_value=datetime.date(2024, 5, 13), input_type=date]     
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
⠋ GraphRAG Indexer
```

### Steps to reproduce

Here is my settings.yaml file
```

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4-turbo-preview
  model_supports_json: true # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  # api_base: https://<instance>.openai.azure.com
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: azure_openai_chat
    model: gpt-4o
    api_base: https://souradip123.openai.azure.com/
    api_version: 2024-05-13
    # organization: <organization_id>
    deployment_name: demotrial
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional
  


chunks:
  size: 300
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 0

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 0

community_report:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # max_tokens: 12000

global_search:
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

```
and my  .env contains 
```
GRAPHRAG_API_BASE=Azure_openai_endpoint
GRAPHRAG_API_VERSION=2024-05-13
GRAPHRAG_API_KEY='AZURE OPEN AI KEY'
```

**Comment by AlonsoGuevara** [comment]
Hi @Souradip121 

The lib is pulling this value `GRAPHRAG_API_VERSION=2024-05-13` and when parsing the API version it is interpreting it as a date.
Can you please try surrounding it by quotes? like `GRAPHRAG_API_VERSION="2024-05-13"`

**Comment by Souradip121** [comment]
raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n", "source": "Columns must be same length as key", "details": null}
Now I am getting this error

**Comment by Souradip121** [comment]
![image](https://github.com/user-attachments/assets/07329482-2726-48c7-a513-e54f25af8157)
Here are my deployment details

**Comment by AlonsoGuevara** [comment]
Can you please share your logs?
Also, check the entity extraction cache, it can be related to faulty entity extraction, resulting in an empty graph.
