### ISSUE TITLE
[Bug]: NotADirectoryError: [Errno 20] Not a directory: '/Users/<user>/Desktop/GraphRag/output/.DS_Store/artifacts/create_final_nodes.parquet'

### ISSUE THREAD

**Issue by Zdong104** [microsoft/graphrag#574]
### Describe the bug

INFO: Reading settings from settings.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/graphrag/query/__main__.py", line 83, in <module>
    run_global_search(
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/graphrag/query/cli.py", line 67, in run_global_search
    final_nodes: pd.DataFrame = pd.read_parquet(
                                ^^^^^^^^^^^^^^^^
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/Users/<user>/Desktop/GraphRag/output/.DS_Store/artifacts/create_final_nodes.parquet'

### Steps to reproduce

python -m graphrag.query --root . --method global "What are the keywords in this chapter? and what is firts foluma in 4.4 Electrical Properties?"

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @Zdibg104
Th .DS_Store file is polluting the path, can you try deleting it a retrying please?
