### ISSUE TITLE
[Bug]: Fail at `create_final_community_reports`

### ISSUE THREAD

**Issue by tiansiyuan** [microsoft/graphrag#647]
### Describe the bug

Fail at step `create_final_community_reports`

In `indexing-engine.log`:

```
16:05:47,160 graphrag.index.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/Users/tiansiyuan/Downloads/projects/graphrag/graphrag/graphrag/index/run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiansiyuan/Library/Caches/pypoetry/virtualenvs/graphrag-it8-biEZ-py3.11/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiansiyuan/Library/Caches/pypoetry/virtualenvs/graphrag-it8-biEZ-py3.11/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiansiyuan/Library/Caches/pypoetry/virtualenvs/graphrag-it8-biEZ-py3.11/lib/python3.11/site-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
                                                     ~~~~~~~~~~~^^^^^^^^
  File "/Users/tiansiyuan/Library/Caches/pypoetry/virtualenvs/graphrag-it8-biEZ-py3.11/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tiansiyuan/Library/Caches/pypoetry/virtualenvs/graphrag-it8-biEZ-py3.11/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
16:05:47,160 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

Two log files are attached.
[indexing-engine.log](https://github.com/user-attachments/files/16330176/indexing-engine.log)
[logs.json](https://github.com/user-attachments/files/16330177/logs.json)

### Steps to reproduce

`poetry run poe index --root .`

### Additional Information

- GraphRAG Version: v0.1.1
- Operating System:  macOS 14.5
- Python Version: 3.11
- Related Issues:

**Comment by heavenwing** [comment]
+1

**Comment by jiangbo721** [comment]
https://github.com/microsoft/graphrag/pull/652
https://github.com/microsoft/graphrag/pull/652/commits/0fb0ccdaa4270cd2ed654cc89f67c4a21353232a

You can change the code like this

**Comment by AlonsoGuevara** [comment]
Hi!

This seems related to OSS LLMs and their response.
We are consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657
