### ISSUE TITLE
[Issue]: <title> ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by prasantpoudel** [microsoft/graphrag#664]
### Describe the issue

when i run the code for prompt tunning i got this error
python -m graphrag.prompt_tune --root . --domain "Manufacturing company" --chunk-size 300 --output prompt_zh

INFO: Reading settings from settings.yaml

Loading Input (InputFileType.text)Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/graphrag/prompt_tune/__main__.py", line 100, in <module>
    loop.run_until_complete(
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/graphrag/prompt_tune/cli.py", line 59, in fine_tune
    await fine_tune_with_config(
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/graphrag/prompt_tune/cli.py", line 109, in fine_tune_with_config
    doc_list = await load_docs_in_chunks(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/graphrag/prompt_tune/loader/input.py", line 56, in load_docs_in_chunks
    chunks_df = chunks_df.sample(n=limit)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/pandas/core/generic.py", line 6118, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphgroq/lib/python3.11/site-packages/pandas/core/sample.py", line 152, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 1001, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by HarlieGirl** [comment]
I got the same issue, wait for the answer

**Comment by AlonsoGuevara** [comment]
Thanks for the report!
This bug has already been addressed and will be released in v0.1.2 
In case that waiting for the next version isn't an option, you can build it from source, or, use the param --limit with a smaller number (default is 15)

For example --limit 5

**Comment by HarlieGirl** [comment]
> Thanks for the report! This bug has already been addressed and will be released in v0.1.2 In case that waiting for the next version isn't an option, you can build it from source, or, use the param --limit with a smaller number (default is 15)
> 
> For example --limit 5

I tried and found that only 1 and 2 are worked,if you set limit 3 or above, than come out the same issue.
