### ISSUE TITLE
Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key

### ISSUE THREAD

**Issue by xldistance** [microsoft/graphrag#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the bug

graphrag0.2 run command python -m graphrag.index --root . Error, it works fine under version 0.1.1
```
10:58:51,93 datashaper.workflow.workflow INFO executing verb cluster_graph
10:58:51,100 graphrag.index.verbs.graph.clustering.cluster_graph WARNING Graph has no nodes
10:58:51,104 datashaper.workflow.workflow ERROR Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "E:\Langchain-Chatchat\glut\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 102, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\indexers\utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
10:58:51,108 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key details=None
10:58:51,108 graphrag.index.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "E:\Langchain-Chatchat\glut\lib\site-packages\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\graphrag\index\verbs\graph\clustering\cluster_graph.py", line 102, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "E:\Langchain-Chatchat\glut\lib\site-packages\pandas\core\indexers\utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
10:58:51,108 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

### GraphRAG Config Used

```
llm:
  # liaobots
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4o-mini-free
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 8_000
  api_base: https://ai.liaobots.work/v1
  # ollama
  #api_key: ${GRAPHRAG_API_KEY}
  #type: openai_chat # or azure_openai_chat
  #model: mistral-nemo:12b
  #model_supports_json: true # recommended if this is available for your model.
  #max_tokens: 8_000
  #api_base: http://localhost:11434/v1
  # request_timeout: 180.0

  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  tokens_per_minute: 900_000 # set a leaky bucket throttle
  requests_per_minute: 9_000 # set a leaky bucket throttle
  max_retries: 10
  max_retry_wait: 10
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: asyncio # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: asyncio # or asyncio
  llm:
    # api_key: sk-9mxwRPHwHt8M1ct7CaCf041d6fC44e9587A041Ca3145E09e
    # type: openai_embedding # or azure_openai_embedding
    # model: text-embedding-ada-002
    # api_base: https://apis.wumingai.com/v1
    api_key: xinference
    type: openai_embedding # or azure_openai_embedding
    model: bge-m3
    api_base: http://127.0.0.1:9997/v1
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional
```

### Additional Information

- GraphRAG Version:0.2
- Operating System:windows11
- Python Version:python3.10
- Related Issues:

**Comment by natoverse** [comment]
We see this issue frequently with other model providers. Please see #657
