### ISSUE TITLE
[Issue]: <title> run index report asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by boystray** [microsoft/graphrag#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

when i index，but always have error.
anyone can help?

File "/root/anaconda3/lib/python3.10/asyncio/locks.py", line 390, in acquire
await fut
asyncio.exceptions.CancelledError

### Steps to reproduce

 poetry run poe index --root . 

### GraphRAG Config Used

```yaml
# Paste your config here

```
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: deepseek-chat
  model_supports_json: false # recommended if this is available for your model.
  api_base: https://api.deepseek.com/v1
  max_tokens: 2000
  concurrent_requests: 1
  tokens_per_minute: 30000
  requests_per_minute: 30
  top_p: 0.99
  max_retries: 3
  max_retry_wait: 10
  sleep_on_rate_limit_recommendation: true

parallelization:
  stagger: 0.3
  num_threads: 30 # the number of threads to use for parallel processing

async_mode: asyncio # or asyncio
chunks:
  size: 1024
  overlap: 20
  group_by_columns: [id] # by default, we don't allow chunks to cross documents

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"

entity_extraction:

  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 0

### Logs and screenshots

Received signal 1, exiting...
⠋ GraphRAG Indexer
├── Loading Input (text) - 3363 files loaded (0 filtered) ━━━━━ 100% 0:0… 0:00:…
├── create_base_text_units
└── create_base_extracted_entities
    └── Verb entity_extract ╸                               3% 102:57:06 2:11:37All tasks cancelled. Exiting...
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/GraphRAG/source/graphrag/graphrag/index/cli.py", line 123, in execute
    async for output in run_pipeline_with_config(
  File "/root/GraphRAG/source/graphrag/graphrag/index/run.py", line 154, in run_pipeline_with_config
    async for table in run_pipeline(
  File "/root/GraphRAG/source/graphrag/graphrag/index/run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
  File "/root/GraphRAG/source/graphrag/graphrag/index/verbs/entities/extraction/entity_extract.py", line 161, in entity_extract
    results = await derive_from_rows(
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/execution/derive_from_rows.py", line 29, in derive_from_rows
    return await derive_from_rows_asyncio(
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/execution/derive_from_rows_asyncio.py", line 41, in derive_from_rows_asyncio
    return await derive_from_rows_base(input, transform, callbacks, gather)
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/execution/derive_from_rows_base.py", line 49, in derive_from_rows_base
    result = await gather(execute)
  File "/root/.cache/pypoetry/virtualenvs/graphrag-ZNpVksep-py3.10/lib/python3.10/site-packages/datashaper/execution/derive_from_rows_asyncio.py", line 39, in gather
    return await asyncio.gather(*tasks)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/GraphRAG/source/graphrag/graphrag/index/__main__.py", line 76, in <module>
    index_cli(
  File "/root/GraphRAG/source/graphrag/graphrag/index/cli.py", line 161, in index_cli
    _run_workflow_async()
  File "/root/GraphRAG/source/graphrag/graphrag/index/cli.py", line 159, in _run_workflow_async
    asyncio.run(execute())
  File "/root/anaconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
asyncio.exceptions.CancelledError

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by boystray** [comment]
i have solve it。the error is a bug of python 3.10. 
with python 3.11,there is no problem.
