### ISSUE TITLE
[Bug]: found and fixed a bug about error generating community report 

### ISSUE THREAD

**Issue by rockyip** [microsoft/graphrag#772]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

I am just using the book.txt from the Get Started section in GraphRag website. And I use ollama for chat completions and embeddings in my local PC.

When generating community_reports,  the LLM return the JSON format correctly like the promts mentioned in community_report.txt. But I still get the error FAILED_TO_CREATE_JSON_ERROR.

Below is one of my JSON response
```
{'title': 'A Community of Family Members', 'summary': 'This community consists of family members, including Bob Cratchit and his wife, who are deeply  
devoted to their youngest son, Tiny Tim. The community also includes the wealthy Mr. Scrooge, who becomes like a second father to Tiny Tim.', 'rating':
6, 'rating_explanation': 'The impact severity rating is moderate due to the presence of both positive and negative relationships within the
community.', 'findings': [{'summary': "Tiny Tim's family is deeply devoted to him", 'explanation': "According to the description of Cratchit's Wife,   
she prioritizes the health and well-being of her husband and their family. This suggests that Tiny Tim's family is caring and supportive towards him   
[Data: Entities (147)]."}, {'summary': 'Tiny Tim is helped by Mr. Scrooge', 'explanation': 'The relationship between Tiny Tim and Mr. Scrooge indicates
that the latter becomes like a second father to the former. This suggests that Tiny Tim receives support and care from Mr. Scrooge [Data: Relationships
(8)].'}, {'summary': "Tiny Tim's health is fragile", 'explanation': "The description of Tiny Tim mentions that he has a physical disability that       
requires an iron frame to support his limbs. This suggests that Tiny Tim's health is fragile and in need of care [Data: Entities (110)]."}, {'summary':
"Cratchit's Wife prioritizes her husband's health", 'explanation': "According to the description of Cratchit's Wife, she is particularly concerned     
about her husband's health. This suggests that she values his physical and emotional well-being [Data: Entities (147)]."}, {'summary': 'Tiny Tim brings
joy to those around him', 'explanation': 'The description of Tiny Tim mentions that he is a cheerful and optimistic child who brings joy to those      
around him. This suggests that Tiny Tim has a positive impact on his community [Data: Entities (110)].'}]}
```

I found that the problem in in graphrag/index/graph/extractors/community_reports/community_reports_extractor.py.
```
response = (
                await self._llm(
                    self._extraction_prompt,
                    json=True,
                    name="create_community_report",
                    variables={self._input_text_key: inputs[self._input_text_key]},
                    is_response_valid=lambda x: dict_has_keys_with_types(
                        x,
                        [
                            ("title", str),
                            ("summary", str),
                            ("findings", list),
                            ("rating", float),
                            ("rating_explanation", str),
                        ],
                    ),
                    model_parameters={"max_tokens": self._max_report_length},
                )
                or {}
            )
```
It validate if the JSON response contains the fields title, summary, findings, rating, rating_explanation.
All fields are existed in my response but the rating is return as integer.
And it will throw error inside the lambda function `dict_has_keys_with_types` when checking the type of the field using `isinstance(value, field_type)`

Therefore, I change the line `("rating", float)` to `("rating", float | int)` and finally I see All workflows completed successfully.
Just a little change. Hope can help

### Steps to reproduce

Just run the index pipeline
python -m graphrag.index --root ./

### GraphRAG Config Used

```yaml

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ollama
  type: openai_chat # or azure_openai_chat
  model: llama3.1
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 4000
  api_base: http://localhost:11434/v1

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: ollama
    type: openai_embedding # or azure_openai_embedding
    model: nomic-embed-text:latest
    api_base: http://localhost:11435/v1 #just craete another port for embeddings using ollama
  
chunks:
  size: 400
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
 

```

### Logs and screenshots

```
00:02:09,419 graphrag.index.graph.extractors.community_reports.community_reports_extract  File "C:\Uor ERROR error generating community report
Traceback (most recent call last):
sers\yip_k\anaconda3\Lib\site-packages\graphrag\index\graph\extractors\community_reports\community_reports_extractor.py", line 58, in __call__
    await self._llm(
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\openai\json_parsing_llm.py", line 34, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\openai\openai_token_replacing_llm.py", line 37, in __call__
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\openai\openai_history_tracking_llm.py", line 33, in __call__
    output = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\base\base_llm.py", line 50, in __call__
    return await self._invoke_json(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yip_k\anaconda3\Lib\site-packages\graphrag\llm\openai\openai_chat_llm.py", line 90, in _invoke_json
    raise RuntimeError(FAILED_TO_CREATE_JSON_ERROR)
RuntimeError: Failed to generate valid JSON output
00:02:09,428 graphrag.index.reporting.file_workflow_callbacks INFO Community Report Extraction Error details=None
00:02:09,428 graphrag.index.verbs.graph.report.strategies.graph_intelligence.run_graph_intelligence WARNING No report found for community: 0
```

### Additional Information

- GraphRAG Version: 0.2.0
- Operating System: Windows 11 Pro
- Python Version: 3.11.7
- Related Issues: error when executing verb create_community_reports

**Comment by natoverse** [comment]
Will link to this from #657 so folks can find it, thanks!
