### ISSUE TITLE
Error with v2.1: FileNotFoundError 

### ISSUE THREAD

**Issue by realSAH** [microsoft/graphrag#837]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

As per getting started, I ran my first command and got this error:

```
╰─ python -m graphrag.index --root ./ragtest
🚀 Reading settings from ragtest\settings.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\index\__main__.py", line 76, in <module>
    index_cli(
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\index\cli.py", line 97, in index_cli
    pipeline_config: str | PipelineConfig = config or _create_default_config(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\index\cli.py", line 249, in _create_default_config
    result = create_pipeline_config(parameters, verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\index\create_pipeline_config.py", line 132, in create_pipeline_config
    *_graph_workflows(settings, embedded_fields),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\index\create_pipeline_config.py", line 305, in _graph_workflows
    "strategy": settings.entity_extraction.resolved_strategy(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aalsaf01\venvs\graphrag_test\Lib\site-packages\graphrag\config\models\entity_extraction_config.py", line 45, in resolved_strategy
    .read_bytes()
     ^^^^^^^^^^^^
  File "C:\Users\aalsaf01\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1050, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aalsaf01\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ragtest\\prompts\\entity_extraction.txt'
⠋ GraphRAG Indexer
```

### Steps to reproduce

`python -m graphrag.index --init --root ./ragtest`

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by realSAH** [comment]
missed `init` command
